#!/bin/bash
set -e
set -x

DBHOST=127.0.0.1
# PROD_DB=
# DEVEL_DB=
# DBUSER=
# DBPASSWORD=
# CLOUD_CREDENTIALS=
# CLOUD_BUCKET=
source dev-dscheduler.conf

# Copy production database, but remove most orders.
make_db() {
    dropdb "$DEVEL_DB"
    createdb "$DEVEL_DB"
    pg_dump "$PROD_DB" | psql --quiet -f - -X "$DEVEL_DB" > /dev/null
    psql --quiet "$DEVEL_DB" -c 'DELETE FROM leases;'
    psql --quiet "$DEVEL_DB" -c "DELETE FROM orders WHERE NOT definition LIKE '%balcony%';"
}

make_db &
./go build github.com/ThomasHabets/qpov/cmd/dscheduler
wait

./dscheduler \
    -db="user=$DBUSER host=$DBHOST password=$DBPASSWORD dbname=$DEVEL_DB sslmode=disable" \
    -port=:9998 \
    -cloud_credentials="$CLOUD_CREDENTIALS" \
    -cloud_bucket="$CLOUD_BUCKET" \
    -cert_file=qpov.retrofitta.se.crt \
    -key_file=qpov.retrofitta.se.key \
    -client_ca_file="$HOME/go/qpov/ca.crt" \
    -rpclog_dir=dev/rpclog/ \
    -secret_TODO=secret \
    -min_lease_renew_time=30s
